config/routes.rb
Rails.application.routes.draw do
  root 'critters#index'
  resources :critters
  resources :cities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :critters
end

app/models/critter.rb
class Critter < ApplicationRecord
  belongs_to :city

  # validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  def index
    @cities = City.all
  end

  def show
  end

  def new
    @city = City.new
  end

  def edit
  end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_city
      @city = City.find(params[:id])
    end

    def city_params
      params.require(:city).permit(:name)
    end
end

app/controllers/critters_controller.rb
class CrittersController < ApplicationController
  before_action :set_critter, only: [:show, :edit, :update, :destroy]

  def index
    @critters = Critter.all.order("LOWER(name)")
  end

  def show
  end

  def new
    @critter = Critter.new
    respond_to :js
  end

  def edit
    respond_to :js
  end

  def create
    @critter = Critter.new(critter_params)
    @critter.save
    respond_to :js
  end

  def update
    @critter.update(critter_params)
    respond_to :js
  end

  def destroy
    @critter.destroy
    respond_to :js
  end

  private
    def set_critter
      @critter = Critter.find(params[:id])
    end

    def critter_params
      params.require(:critter).permit(:name, :city_id, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/critters_helper.rb
module CrittersHelper
  def display_description(critter)
    vowels = %w(a e i o u h)
    indefinite_article = 'a'
    indefinite_article = 'an' if critter.color.present? && vowels.include?(critter.color[0].downcase)

    preposition = 'in'
    preposition = 'on' if critter.city.name.downcase.match('isla')

    "is #{indefinite_article} #{critter.color} critter who lives #{preposition} #{critter.city.name}"
  end
end

app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/critters/_critter.html.erb
<tr id="critter_<%= critter.id %>">
  <td><h4 class="name"><%= critter.name %></h4></td>
  <td><%= display_description(critter) %></td>
  <td><%= link_to 'Edit', edit_critter_path(critter), remote: true %></td>
  <td><%= link_to 'Delete', critter, method: :delete, data: { confirm: "Are you sure you want to delete #{critter.name}? There is no undo." }, remote: true %></td>
</tr>

app/views/critters/_edit.html.erb
<tr id="edit-form-<%= @critter.id %>" class="form-holder">
  <td colspan='4'>
    <%= render 'form', critter: @critter %>
  </td>
</tr>

app/views/critters/_form.html.erb
<%= link_to 'Cancel', '', id: 'dismiss-form', class: 'btn btn-sm btn-primary right' %>
<%= form_for(critter, remote: true) do |f| %>
  <% if critter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(critter.errors.count, "error") %> prohibited this critter from being saved:</h2>

      <ul>
      <% critter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field col-sm-6">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="field col-sm-6">
      <%= f.label :color %>
      <%= f.text_field :color, class: 'form-control'  %>
    </div>
  </div> <!-- row -->

  <div class="row">
    <div class="field col-sm-12">
      <%= f.label :city %> (<%= link_to 'New City', new_city_path, remote: true %>)<br>
      <%= f.collection_radio_buttons :city_id, City.all.order(:name), :id, :name  %>
      <%#= f.collection_select :city_id, City.all.order(:name), :id, :name, class: 'form-control'  %>
    </div>
  </div> <!-- row -->

  <div class="actions">
    <%= f.submit class: 'btn btn-sm btn-success' %>
  </div>
<% end %>

app/views/critters/_new.html.erb
<div class="form-holder">
  <h3>New Critter</h3>
  <%= render 'form', critter: @critter %>
</div>

app/views/critters/create.js.erb
// vanilla javascript version

document.querySelector('tbody#critters').insertAdjacentHTML('afterbegin', "<%= escape_javascript(render partial: 'critter', locals: {critter: @critter} ) %>");

document.getElementById("new-form-placeholder").innerHTML = ""


// jQuery version

// $('tbody#critters').prepend("<%= escape_javascript(render partial: 'critter', locals: {critter: @critter} ) %>");

// document.getElementById("critter-form-placeholder").style.display = "none";

app/views/critters/destroy.js.erb
// vanilla js version
document.querySelector("#critter_<%= @critter.id %>").remove()

// jquery version

// $("#critter_<%= @critter.id %>").remove();

app/views/critters/edit.js.erb
// vanilla JS version

document.querySelector("#critter_<%= @critter.id %>").insertAdjacentHTML('afterend', "<%= escape_javascript(render partial: 'edit') %>")



// jQuery version

// $("<%= escape_javascript(render partial: 'edit') %>").insertAfter("#critter_<%= @critter.id %>");

app/views/critters/index.html.erb
<p id="notice"><%= notice %></p>

<div class="right"><%= link_to '+ New Critter', new_critter_path, remote: true, class: 'btn btn-sm btn-primary' %></div>

<h1>Critters</h1>
<div class="filter">
  <label>On-Page Javascript Filtering:</label>
  <input type="text" name="filter" id="filter" placeholder="Filter by Critter Name" class="form-control"><br>
  <%= link_to 'Reset', '', class: 'btn btn-sm btn-secondary', id: 'reset-button' %>
</div> <!-- filter -->

<div id="new-form-placeholder"></div>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>About</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody id="critters" >
    <% @critters.each do |critter| %>
      <%= render 'critter', critter: critter %>
    <% end %>
  </tbody>
</table>

app/views/critters/new.js.erb
// vanilla JS version

document.getElementById("new-form-placeholder").innerHTML = "<%= escape_javascript(render partial: 'new' ) %>"


// jQuery version

// $('#new-form-placeholder').html("<%= escape_javascript(render partial: 'new' ) %>");

// document.getElementById("new-form-placeholder").style.display = "block";

app/views/critters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @critter.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @critter.city %>
</p>

<p>
  <strong>Color:</strong>
  <%= @critter.color %>
</p>

<%= link_to 'Edit', edit_critter_path(@critter) %> |
<%= link_to 'Back', critters_path %>

app/views/critters/update.js.erb
// vanilla JS version

document.querySelector("#critter_<%= @critter.id %>").outerHTML = "<%= escape_javascript(render partial: 'critter', locals: {critter: @critter} ) %>"

document.querySelector("#edit-form-<%= @critter.id %>").remove()

// jQuery version

// $("#critter_<%= @critter.id %>").replaceWith("<%= escape_javascript(render partial: 'critter', locals: {critter: @critter} ) %>")

// $("#edit-form-<%= @critter.id %>").remove()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SinglePageCrud</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>